<?php
/**
 * FME Instant Search
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   FME
 * @package    Instant Search
 * @author     Muhammad Qaisar Satti <shumail123@gmail.com>
 *         
 * @copyright  Copyright 2015 © www.fmeextensions.com All right reserved
 */
$catalogSearchHelper =  $this->helper('catalogsearch');
?>
 <?php if(Mage::helper('instantsearch')->getsearchurl()!='1') { ?>
<form id="search_mini_form" action="<?php  echo $catalogSearchHelper->getResultUrl() ?>" method="get"><?php } ?>
    <div class="input-box">
      <?php if(Mage::helper('instantsearch')->getsearchurl()!='1') { ?>  <label for="search"><?php echo $this->__('Search:') ?></label><?php } ?>
        <input id="search" type="search" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="input-text required-entry" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" placeholder="<?php echo $this->__('Search entire store here...') ?>" autocomplete="off"  />
        <?php if(Mage::helper('instantsearch')->getsearchurl()!='1') { ?>
        <button type="submit" title="<?php echo $this->__('Search') ?>" class="button search-button"><span><span><?php echo $this->__('Search') ?></span></span></button><?php } ?>
    </div>

  
</form>
<div class="clearfix"></div>
<div id="searchcontent"></div>
<script type="text/javascript">
    //<![CDATA[
        var instantsearch = new Instantsearch(
        '<?php echo $this->getUrl('instantsearch/index') ?>',
        
        'search'
    );
    
    Event.observe('search', 'keyup', function(event){           
        instantsearch.search();     
    });

    //]]>
    </script>
   