<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Onestepcheckout
 * @version     0.1.9
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 * */
?>
<?php echo $this->getChildHtml('items_before'); ?>
<div id="checkout-review-table-wrapper">
    <table  class="onestepcheckout-summary" id="checkout-review-table">
        <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
        <col />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
        <col width="1" />
        <col width="1" />
        <?php endif; ?>
        <thead>
            <tr>
                <th rowspan="<?php echo $rowspan ?>" class="name"><?php echo $this->__('Product Name') ?></th>
                <th colspan="<?php echo $colspan ?>" class="price"><?php echo $this->__('Price') ?></th>
                <th rowspan="<?php echo $rowspan ?>" class="qty"><?php echo $this->__('Qty') ?></th>
                <th colspan="<?php echo $colspan ?>" class="total"><?php echo $this->__('Subtotal') ?></th>
            </tr>
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <tr>
                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                </tr>
            <?php endif; ?>
        </thead>
        <?php echo $this->getChildHtml('totals'); ?>
        <tbody>
        <?php foreach($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item)?>
        <?php endforeach ?>
        </tbody>
    </table>
     <div class="shopping-cart-price-block">
         <?php 
            Mage::getSingleton('checkout/session')->unsetAll();
            $quote = Mage::getModel('checkout/session')->getQuote();
            $quoteData= $quote->getData();
            
            $appliedRuleIds = Mage::getSingleton('checkout/session')->getQuote()->getAppliedRuleIds();
            $shopping_cart_rule_ids = array('15','16','17');
            $appliedRuleIds = explode(',', $appliedRuleIds);
            $result_id = array_values(array_intersect($shopping_cart_rule_ids,$appliedRuleIds));

            if(!empty($result_id[0]))
            {
                $oRule = Mage::getModel('salesrule/rule')->load($result_id[0]);
                $shopping_rule_condition = unserialize($oRule->getConditionsSerialized());

                $min_shopping_price = $shopping_rule_condition['conditions'][0]['value'];
                $max_shopping_price = $shopping_rule_condition['conditions'][1]['value'];

                if($result_id[0] == 15)
                {
                    $oRule = Mage::getModel('salesrule/rule')->load('16');
                    $shopping_rule_condition = unserialize($oRule->getConditionsSerialized());
                    $discount_percentage = "7%";
                    $condition_max_eligible_shopping = $shopping_rule_condition['conditions'][0]['value'];
                    
                $min_price = abs($quoteData['subtotal'] - $condition_max_eligible_shopping);
                $message =  "Add " .$this->helper('checkout')->formatPrice($min_price) ." more to get <span class='more_discount_percentage'>" .$discount_percentage ."</span> off";
                }
                else if($result_id[0] == 16)
                {
                    $oRule = Mage::getModel('salesrule/rule')->load('17');
                    $shopping_rule_condition = unserialize($oRule->getConditionsSerialized());
                    $discount_percentage = "10%";
                    $condition_max_eligible_shopping = $shopping_rule_condition['conditions'][0]['value'];
                    
                $min_price = abs($quoteData['subtotal'] - $condition_max_eligible_shopping);
                $message =  "Add " .$this->helper('checkout')->formatPrice($min_price) ." more to get <span class='more_discount_percentage'>" .$discount_percentage ."</span> off";
                }
                else if($result_id[0] == 17 && $quoteData['subtotal'] < 1500 )
                {
                    $oRule = Mage::getModel('salesrule/rule')->load('17');
                    $shopping_rule_condition = unserialize($oRule->getConditionsSerialized());
                    $discount_percentage = "10%";
                    $condition_max_eligible_shopping = $shopping_rule_condition['conditions'][0]['value'];
                    
                $min_price = abs($quoteData['subtotal'] - $condition_max_eligible_shopping);
                $message =  "Add " .$this->helper('checkout')->formatPrice($min_price) ." more to get <span class='more_discount_percentage'>" .$discount_percentage ."</span> off";
                }
                else if($result_id[0] == 17 && $quoteData['subtotal'] > 1500 )
                {
                    $percentage = 100;

                    $min_shopping_price = 0;
                    $max_shopping_price = 1501;
                    $message = "You have succesfully Qualified for maxium current discount available in the store";
                }
                else if($result_id[0] == 27)
                {
                    $oRule = Mage::getModel('salesrule/rule')->load('15');
                    $shopping_rule_condition = unserialize($oRule->getConditionsSerialized());
                    $discount_percentage = "5%";
                    $condition_max_eligible_shopping = $shopping_rule_condition['conditions'][0]['value'];
                    
                $min_price = abs($quoteData['subtotal'] - $condition_max_eligible_shopping);
                $message =  "Add " .$this->helper('checkout')->formatPrice($min_price) ." more to get <span class='more_discount_percentage'>" .$discount_percentage ."</span> off";
                }            
            }
            else
            {
                $oRule = Mage::getModel('salesrule/rule')->load('15');
                $shopping_rule_condition = unserialize($oRule->getConditionsSerialized());
                $discount_percentage = "5%";
                $condition_max_eligible_shopping = $shopping_rule_condition['conditions'][0]['value'];
                $min_price = abs($quoteData['subtotal'] - $condition_max_eligible_shopping);
                $message =  "Add " .$this->helper('checkout')->formatPrice($min_price) ." more to get <span class='more_discount_percentage'>" .$discount_percentage ."</span> off";
                $max_shopping_price = 500;
                $min_shopping_price = 5;

            }

            if($quoteData['subtotal'] > 1500)
            {
                $percentage = 100;
            }else
            {
                $range = $max_shopping_price - $min_shopping_price;
                $correctedStartValue = $quoteData['subtotal'] - $min_shopping_price;
                $percentage = ($correctedStartValue * 100) / $range;
            }
        ?>
        <div class="shopping_cart_rule">
            <div class="range">
                <span class="min-range"><?php echo $this->helper('checkout')->formatPrice($min_shopping_price);?></span>
                <span class="max-range"><?php echo $this->helper('checkout')->formatPrice($max_shopping_price);?></span>
            </div>
            <div class="progress">
                <div class="progress-bar purchase" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:<?php echo round($percentage,0,PHP_ROUND_HALF_UP)."%"; ?>">
                </div>
            </div>
            <div class="info-block">
                <div class="block-info"><?php echo $message; ?> </div>
            </div>
        </div>
    </div>
</div>
<p class="tail" >You will earn <?php $p= Mage::getModel("rewards/checkout_earn")->getEarnPoints(Mage::getSingleton('checkout/session')->getQuote()->getBillingAddress());echo $p;?> R-Coins after this order</p>
<?php echo $this->getChildHtml('items_after'); ?>
<script type="text/javascript">
//<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
//]]>
</script>


