<?php
$shouldWarnGuest = $this->getShowWarningTextMessage();
?>
<?php if ($points = $this->getEarnPoints()&&0): ?>
    <tr>
        <td class="a-right cart-points-total_earned" colspan="<?php echo $this->getColspan(); ?>">
            <div class=""><b><?php echo $this->__('You Earn') ?></b></div>
        </td>
        <td style="" class="a-right cart-points-total_earned">
            <span class="price">
                <?php echo Mage::helper('rewards')->formatPoints($points) ?>
            </span>
        </td>
    </tr>
<?php endif; ?>
