
<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <?php 
			echo $this->__('You will be redirected to CCAvenue payment website when you place an order.') ?>
        </li>
		<p><img src="https://www.ccavenue.com/images_shoppingcart/ccavenue_pay_options.gif"/></p>
		
    </ul>
</fieldset> 
