<?php
if (!$this->getMaxPointsNumberToSpent() || !$this->getIsSpendAllowed()) {
    return;
}
?>

<?php if (!Mage::app()->getRequest()->isXmlHttpRequest()) { ?>
<style>
    form#amscheckout-onepage div#amscheckout-main.amscheckout-main div.amscheckout div.three-columns div.second-column div.column-section div#checkout-coupon.coupon div.onestepcheckout-rewards {
        position: relative;
        left: -10px;
    }

    form#amscheckout-onepage div#amscheckout-main.amscheckout-main div.amscheckout div.three-columns div.second-column div.column-section div#checkout-coupon.coupon div.onestepcheckout-rewards div.discount div.discount-form {
        margin-left: 10px;
        margin-top: 10px;
    }

    form#amscheckout-onepage div#amscheckout-main.amscheckout-main div.amscheckout div.three-columns div.second-column div.column-section div#checkout-coupon.coupon div.onestepcheckout-rewards div.discount div.discount-form button.amscheckout-apply span {
        padding: 1px;
    }

    form#amscheckout-onepage div#amscheckout-main.amscheckout-main div.amscheckout div.three-columns div.second-column div.column-section div#checkout-coupon.coupon div.onestepcheckout-rewards div.discount div.discount-form button.amscheckout-apply span span {
        padding: 10px;
    }

    .amscheckout-main .onestepcheckout-rewards{
        margin-top: 40px;
        margin-bottom: 20px;
    }
    .amscheckout-main .onestepcheckout-rewards .area-header{
        margin-left: -10px;
    }
    .amscheckout-main .onestepcheckout-rewards label[for="points_all"]{
        vertical-align: text-top;
    }
    .amscheckout-main .onestepcheckout-rewards #points_all{
        width: inherit;
        display: inline-block;
    }

    .rewards-max-block label{
        max-width: inherit;
        float: left;
        margin-top: 10px;
        margin-left: 5px;
    }

    .rewards-max-block input{
        width: inherit;
        float: left;
    }
</style>
<?php } ?>

<div class="onestepcheckout-rewards">
    <div class="discount">
        <div class="area-header">
            <div class="amscheckout-img-shadow">
                <div class="amscheckout-img">%</div>
            </div>
            <?php echo $this->__('Use Reward Points') ?>
        </div>
        <div class="discount-form">
            <label for="points_amount"><?php echo $this->__('You have <b>%s</b> available.', Mage::helper('rewards')->formatPoints($this->getBalancePoints())) ?><br>

            <?php echo $this->__('Enter amount of points to spend:'); ?>
            </label>
            <div class="input-box">
                <input class="input-text" id="points_amount" name="points_amount" value="<?php echo $this->getPointsAmount() ? $this->htmlEscape($this->getPointsAmount()) : '' ?>" />
            </div>
            <div class="input-box" style="margin-top: 5px; margin-bottom: 5px;">
                <input type='checkbox' id="points_all" name="points_all"
                <?php echo $this->getPointsAmount() == $this->getMaxPointsNumberToSpent() ? 'checked' : ''?> />
                <label for="points_all"><?php echo $this->__('Use maximum %s', Mage::helper('rewards')->formatPoints($this->getMaxPointsNumberToSpent()))?></label>
            </div>
                <button id="onestepcheckout-rewards-add" type="button" title="<?php echo $this->__('Apply Points') ?>" class="amscheckout-apply" value="<?php echo $this->__('Apply Points') ?>"><span><span><?php echo $this->__('Apply Points') ?></span></span></button>
                <span id="cancel_block" <?php echo $this->getPointsAmount() ? '' : 'style="display:none"' ?>>
                    &nbsp; <button id="onestepcheckout-rewards-cancel" type="button" title="<?php echo $this->__('Cancel Points') ?>" class="amscheckout-apply" value="<?php echo $this->__('Cancel Points') ?>"><span><span><?php echo $this->__('Cancel Points') ?></span></span></button>
                </span>
        </div>
    </div>

    <?php if (!Mage::app()->getRequest()->isXmlHttpRequest()) { ?>
        <script type="text/javascript">
            //<![CDATA[
            var rewardsForm = new VarienForm('reward-points-form');
            var maxPointsNumberToSpent = <?php echo $this->getMaxPointsNumberToSpent() ?>;
            //]]>
            Event.observe(window, 'load', function() {
                document.observe('keyup', function(e, el) {
                    if (el = e.findElement('#points_amount')) {
                        var val = parseInt($('points_amount').value);
                        if (isNaN(val) || val < maxPointsNumberToSpent) {
                            $('points_all').checked = false;
                        } else {
                            $('points_all').checked = true;
                            $('points_amount').value = maxPointsNumberToSpent;
                        }
                    }
                });
                document.observe('click', function(e, el) {
                    if (el = e.findElement('#onestepcheckout-rewards-add')) {
                        $('points_amount').addClassName('required-entry');
                        updatePoints();
                    }
                    if (el = e.findElement('#onestepcheckout-rewards-cancel')) {
                        $('points_amount').removeClassName('required-entry');
                        $('points_amount').setValue('');
                        $('points_all').checked = false;
                        updatePoints();
                    }
                    if (el = e.findElement('#points_all')) {
                        if ($('points_amount').value == maxPointsNumberToSpent) {
                            $('points_amount').value = '';
                        } else {
                            $('points_amount').value = maxPointsNumberToSpent;
                        }
                    }
                });
            });

            function updatePoints() {
                var points_amount = $('points_amount').getValue();
                if (points_amount > 0) {
                    $('cancel_block').show();
                } else {
                    $('cancel_block').hide();
                }

                var url = '<?php echo $this->getUrl('rewards/checkout/applyPointsAitocOnestepcheckout', array('_secure' => true)) ?>';
                var parameters = {points_amount: points_amount};

                new Ajax.Request(url, {
                    method: 'post',
                    parameters: parameters,
                    onSuccess: function(transport) {
                        // updateCheckout("shipping_method");
                        updateCheckout("payment_method");
                    }
                });
            }
            var open = window.XMLHttpRequest.prototype.open;
            window.XMLHttpRequest.prototype.open = function (method, url, async, user, pass) {
                this.addEventListener("readystatechange", function() {
                    if (this.readyState === 4) {
                        try {
                            var config = this.responseText.evalJSON();
                        } catch (e) {
                            var config = {html: false};
                        }

                        if (config.html) {
                            if (config.html.payment_method) {
                                var parameters = {'module': 'Amasty_Scheckout'};
                                var requestUrl = '<?php echo $this->getUrl('rewards/checkout/updateRewardsBlock', array('_secure' => true)) ?>';
                                if (requestUrl != url) {
                                    new Ajax.Request(requestUrl, {
                                        method: 'post',
                                        parameters: parameters,
                                        onSuccess: function (transport) {
                                            var data = transport.responseText.evalJSON();
                                            maxPointsNumberToSpent = data.max_points;
                                            $$('.onestepcheckout-rewards')[0].replace(data.html);
                                        }
                                    });
                                }
                            }
                        }
                    }
                }, false);
                open.apply(this, arguments);
            };
        </script>
    <?php } ?>
</div>
