<?php
if (!$this->getMaxPointsNumberToSpent()) {
    return;
}
$secure = Mage::app()->getFrontController()->getRequest()->isSecure();
?>
<div id="coupon-discount" class="glc-step rewards">
    <p class="aw-onestepcheckout-number aw-onestepcheckout-number-4"><?php echo $this->__('Use Reward Points') ?></p>
    <div class="discount-form" id="discount-code">
        <?php
        echo $this->getMessagesBlock()->getGroupedHtml();
        $this->getMessagesBlock()->getMessageCollection()->clear();
        ?>
        <label for="points_amount"><?php echo $this->__('You have <b>%s</b> available.', Mage::helper('rewards')->formatPoints($this->getBalancePoints())) ?><br>
            <?php echo $this->__('Enter amount of points to spend:'); ?>
        </label>
        <input type="hidden" name="remove-points" id="remove-points" value="0" />
        <div class="input-box">
            <input class="input-text" id="points_amount" name="points_amount" value="<?php echo $this->getPointsAmount() ? $this->htmlEscape($this->getPointsAmount()) : '' ?>" style="width: 90%;"/>
        </div>
        <div class="input-box">
            <input type='checkbox' id="points_all" name="points_all"
                <?php echo $this->getPointsAmount() == $this->getMaxPointsNumberToSpent() ? 'checked' : ''?> />
            <label for="points_all"><?php echo $this->__('Use maximum %s', Mage::helper('rewards')->formatPoints($this->getMaxPointsNumberToSpent()))?></label>
        </div>
        <div>
            <button type="button" title="<?php echo $this->__('Apply Points') ?>"  id="apply_points" class="button" value="<?php echo $this->__('Apply Points') ?>"><span><span><?php echo $this->__('Apply') ?></span></span></button>

            &nbsp; <button type="button" <?php if (!$this->getPointsAmount()): ?>style="display: none;"<?php endif?> title="<?php echo $this->__('Cancel Points') ?>"  id="cancel_points"  class="button" value="<?php echo $this->__('Cancel Points') ?>"><span><span><?php echo $this->__('Cancel') ?></span></span></button>

        </div>
    </div>
    <script type="text/javascript">
        //<![CDATA[

        <?php if ($this->getIsComplexDiscountDisabled()): ?>
        function handleDiscount() {
            if(document.getElementById('aw-onestepcheckout-review-coupon')) {
                var couponBlock = document.getElementById('aw-onestepcheckout-review-coupon');
                var val = parseInt($('points_amount').value);
                if(isNaN(val)) {
                    couponBlock.style.display = 'block';
                } else {
                    couponBlock.style.display = 'none';
                }
            }
        }

        function handleRewardBlock() {
            if(document.getElementById('aw-onestepcheckout-review-coupon')) {
                var rewardsBlock = document.getElementsByClassName('rewards').item(0);
                var couponBlock = document.getElementById('aw-onestepcheckout-review-coupon');
                var discountText = couponBlock.getElementsByClassName('coupon-code-form')[0].getElementsByClassName('input-box')[0].getElementsByClassName('input-text')[0];

                if(discountText.getValue() == '') {
                    rewardsBlock.style.display = 'block';
                } else {
                    rewardsBlock.style.display = 'none';
                }
            }
        }

        window.onload = function() {
            handleDiscount();
            handleRewardBlock();
        }

        document.addEventListener('DOMNodeInserted', function (evt) {
            if(evt.target.id == "aw-onestepcheckout-review-coupon") {
                handleDiscount();
            }
        });

        document.addEventListener('keypress', function (evt) {
            if((evt.keyCode == 13) && (evt.target instanceof  HTMLInputElement) && (evt.target.id == 'coupon_code')) {
                handleRewardBlock();
            }
        });
        <?php endif ?>

        Event.observe($('points_all'), 'click', function(){
            if ($('points_amount').value == <?php echo $this->getMaxPointsNumberToSpent() ?>) {
                $('points_amount').value = '';
            } else {
                $('points_amount').value = <?php echo $this->getMaxPointsNumberToSpent() ?>;
            }
        });
        Event.observe($('points_amount'), 'keyup', function(){
            var val = parseInt($('points_amount').value);
            if (isNaN(val) || val < <?php echo $this->getMaxPointsNumberToSpent() ?>) {
                $('points_all').checked = false;
            } else {
                $('points_all').checked = true;
                $('points_amount').value = <?php echo $this->getMaxPointsNumberToSpent() ?>;
            }
        });

        $('apply_points') && $('apply_points').observe('click', function(e) {
            updatePoints();
            awOSCPayment.savePayment();
        });

        $('cancel_points') && $('cancel_points').observe('click', function(e) {
            $('points_amount').value = '';
            updatePoints();
            awOSCPayment.savePayment();
        });

        function updatePoints() {
            var url = '<?php echo $this->getUrl('rewards/checkout/applyPointsGoMageLightcheckout', array('_secure' => true)) ?>';
            var parameters = {points_amount: $('points_amount').value};

            if (typeof AWOnestepcheckoutCore != 'undefined') {
                AWOnestepcheckoutCore.updater.startRequest(url, {
                    method: 'post',
                    parameters: parameters,
                    onComplete: function (transport) {
                        if (transport.status == 200) {

                            var response = transport.responseText.evalJSON();

                            if (response.success) {
                                if ($('points_amount').value != '') {
                                    $('cancel_points').show();
                                } else {
                                    $('points_all').checked = false;
                                    $('cancel_points').hide();
                                }
                            }
                            AWOnestepcheckoutCore.updater.addActionBlocksToQueue('applyPointsGoMageLightcheckout');
                            AWOnestepcheckoutCore.updater.removeActionBlocksFromQueue('applyPointsGoMageLightcheckout', response);
                        }
                    }
                });
            } else {
                new Ajax.Request(url, {
                    method: 'post',
                    parameters: parameters,
                    onSuccess: function (transport) {
                        if (transport.status == 200) {

                            var response = transport.responseText.evalJSON();

                            if (response.success) {
                                if ($('points_amount').value != '') {
                                    $('cancel_points').show();
                                } else {
                                    $('points_all').checked = false;
                                    $('cancel_points').hide();
                                }
                            }
                        }
                    }
                });
            }
        }
        //]]>
    </script>
</div>
