<?php
if (!$this->getMaxPointsNumberToSpent()) {
    return;
}
$secure = Mage::app()->getFrontController()->getRequest()->isSecure();
?>
<div id="coupon-discount" class="glc-step rewards">
    <h2 class="glc-title"><span id="glc-rewards-number" class="glc-number">4</span><strong><?php echo $this->__('Use Reward Points') ?></strong></h2>
    <div class="discount-form" id="discount-code">
        <?php
        echo $this->getMessagesBlock()->getGroupedHtml();
        $this->getMessagesBlock()->getMessageCollection()->clear();
        ?>
        <label for="points_amount"><?php echo $this->__('You have <b>%s</b> available.', Mage::helper('rewards')->formatPoints($this->getBalancePoints())) ?><br>
            <?php echo $this->__('Enter amount of points to spend:'); ?>
        </label>
        <input type="hidden" name="remove-points" id="remove-points" value="0" />
        <div class="input-box">
            <input class="input-text" id="points_amount" name="points_amount" value="<?php echo $this->getPointsAmount() ? $this->htmlEscape($this->getPointsAmount()) : '' ?>" style="width: 90%;"/>
        </div>
        <div class="input-box">
            <input type='checkbox' id="points_all" name="points_all"
                <?php echo $this->getPointsAmount() == $this->getMaxPointsNumberToSpent() ? 'checked' : ''?> />
            <label for="points_all"><?php echo $this->__('Use maximum %s', Mage::helper('rewards')->formatPoints($this->getMaxPointsNumberToSpent()))?></label>
        </div>
        <div>
            <button type="button" title="<?php echo $this->__('Apply Points') ?>"  id="apply_points" class="button" value="<?php echo $this->__('Apply Points') ?>"><span><span><?php echo $this->__('Apply Points') ?></span></span></button>

            &nbsp; <button type="button" <?php if (!$this->getPointsAmount()): ?>style="display: none;"<?php endif?> title="<?php echo $this->__('Cancel Points') ?>"  id="cancel_points"  class="button" value="<?php echo $this->__('Cancel Points') ?>"><span><span><?php echo $this->__('Cancel Points') ?></span></span></button>

        </div>
    </div>
    <script type="text/javascript">
        //<![CDATA[

        <?php if ($this->getIsComplexDiscountDisabled()): ?>
            <!-- additional script to hide AJAX-based coupon box -->
            function handleDiscount() {
                if(document.getElementsByClassName('lightcheckout-discount-form').length > 0) {
                    var couponBlock = document.getElementsByClassName('lightcheckout-discount-form').item(0);
                    var val = parseInt($('points_amount').value);
                    if(isNaN(val)) {
                        couponBlock.style.display = 'block';
                    } else {
                        couponBlock.style.display = 'none';
                    }
                }
            }

            function handleRewardBlock(force) {
                if(document.getElementsByClassName('lightcheckout-discount-form').length > 0) {
                    var rewardsBlock = document.getElementsByClassName('rewards').item(0);
                    var couponBlock = document.getElementsByClassName('lightcheckout-discount-form').item(0);
                    var discountText = couponBlock.getElementsByClassName('input-box')[0].getElementsByClassName('input-text')[0];

                    if(discountText.getValue() == '' || force) {
                        rewardsBlock.style.display = 'block';
                    } else {
                        rewardsBlock.style.display = 'none';
                    }
                }
            }

            window.onload = function() {
                handleDiscount();
                handleRewardBlock(false);
            }

            document.addEventListener('DOMNodeInserted', function (evt) {
                if(evt.target.className == "discount") {
                    handleDiscount();
                }
            });

            document.addEventListener('click', function (evt) {
                if(evt.target instanceof HTMLButtonElement)
                {
                    if(evt.target.parentElement.className == 'lightcheckout-discount-form') {
                        var forced = evt.target.getAttribute('onclick').indexOf('coupon_code');
                        handleRewardBlock(forced == -1);
                    }
                }
            });
        <?php endif ?>

        Event.observe($('points_all'), 'click', function(){
            if ($('points_amount').value == <?php echo $this->getMaxPointsNumberToSpent() ?>) {
                $('points_amount').value = '';
            } else {
                $('points_amount').value = <?php echo $this->getMaxPointsNumberToSpent() ?>;
            }
        });
        Event.observe($('points_amount'), 'keyup', function(){
            var val = parseInt($('points_amount').value);
            if (isNaN(val) || val < <?php echo $this->getMaxPointsNumberToSpent() ?>) {
                $('points_all').checked = false;
            } else {
                $('points_all').checked = true;
                $('points_amount').value = <?php echo $this->getMaxPointsNumberToSpent() ?>;
            }
        });

        $('apply_points') && $('apply_points').observe('click', function(e) {
            updatePoints();
        });

        $('cancel_points') && $('cancel_points').observe('click', function(e) {
            $('points_amount').value = '';
            updatePoints();
        });

        function updatePoints() {
            var url = '<?php echo $this->getUrl('rewards/checkout/applyPointsGoMageLightcheckout', array('_secure' => true)) ?>';
            var parameters = {points_amount: $('points_amount').value};

            new Ajax.Request(url, {
                method: 'post',
                parameters: parameters,
                onSuccess: function(transport) {
                    if(transport.status == 200) {

                        var response = transport.responseText.evalJSON();

                        if(response.success) {
                            checkout.submit(checkout.getFormData(), 'get_totals');
                            if($('points_amount').value != '') {
                                $('cancel_points').show();
                            } else {
                                $('points_all').checked = false;
                                $('cancel_points').hide();
                            }
                        }
                    }
                }
            });
        }
        //]]>
    </script>
</div>
