<?php

$helper = Mage::helper('mobilelogin');?>
    <!-- The Modal -->
    <div id="mobilemodal" class="mobilemodal">
        <!-- Modal content -->
        <div class="mobilemodal-content">
            <div class="mobilepopup-header">
                <input type="hidden" name="otptype" id="otptype" value="forgot">
                <span class="mobilelogin-close">&times;</span>
                <h1 class="mobilepopup-title"><?php echo $this->__('Forgot Password'); ?></h1>
                <span id="mobilelogin-popup-message"></span>
            </div>
            <div class="mobilelogin-otpsend">
                <div class="mobilepopup-content">
                    <li class="mobilenumber-container">
                        <label for="mobilenumber" class="required"><em>*</em><?php echo $this->__('Mobile Number (Without Country Code)') ?>
                        </label>
                        <div class="input-box">
                            <input type="text" class="mobile-input" name="mobilenumber" id="mobilenumber"
                                   value="<?php  ?>"
                                   title="<?php echo Mage::helper('core')->quoteEscape($this->__('Mobile Number')) ?>"
                                   class="input-text validate-email required-entry"/>

                            <span class="mobilelogin-error"><?php echo $this->__('Enter Valid Mobile') ?></span>

                        </div>
                    </li>
                </div>
                <div class="mobilepopup-footer footerlinks">
                    <input type="button" class="button sendotp" name="sendotp" id="sendotp"
                           value="<?php echo $this->__('Send Otp') ?>"/>
                    <input type="button" class="button" name="forgotEmail" id="forgotEmail"
                           value="<?php echo $this->__('Reset Using Email') ?>"/>
                </div>
            </div>
            <div class="mobile-otpverify">
                <li class="mobilenumber-container">
                    <label for="otpverify" class="required"><em>*</em><?php echo $this->__('Verify OTP') ?>
                    </label>
                    <div class="input-box">
                        <input type="text" class="mobile-input" name="inputotpverify" id="inputotpverify"
                               value="" class="input-text required-entry"/>
                    </div>
                    <div class="mobilepopup-footer">
                        <input type="button" class="button" name="btnverifyotp" id="btnverifyotp"
                               value="<?php echo $this->__("Verify Otp"); ?>"/>
                        <input type="button" class="button sendotp" name="resendotp" id="resendotp"
                               value="<?php echo $this->__("Resend Otp"); ?>"/>
                    </div>
                </li>
            </div>
            <div class="mobile-password">
                <li class="mobilenumber-container">
                    <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?>
                    </label>
                    <div class="input-box">
                        <input type="password" class="mobile-input" name="mobpassword" id="mobpassword"
                               value="" class="input-text required-entry"/>
                    </div>
                    <label for="confirmpassword" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?>
                    </label>
                    <div class="input-box">
                        <input type="password" class="mobile-input" name="mobrepassword" id="mobrepassword"
                               value="" class="input-text required-entry"/>
                    </div>
                    <div class="mobilepopup-footer">
                        <input type="button" class="button" name="changepassword" id="changepassword"
                               value="<?php echo $this->__("change password"); ?>"/>
                    </div>
                </li>
            </div>

        </div>
    </div>
    <?php $loaderPath = $this->getSkinUrl('images/ajax-loader.gif', array('_secure' => true)) ?>
    <div class="mobileloader">
        <div id="wait"
             style="display:none;width:69px;height:89px;z-index: 9999999999999;position:absolute;top:50%;left:50%;padding:2px;">
            <img src='<?php echo $loaderPath; ?>' width="64" height="64"/><br>Loading..
        </div>
    </div>
<div class="mobile-forgotpasswd">
    <div class="page-title">
        <h1><?php echo $this->__('Forgot Your Password?') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
        <div class="fieldset">
            <h2 class="legend"><?php echo $this->__('Retrieve your password here') ?></h2>
            <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
            <ul class="form-list">
                <li>
                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?>
                    </label>
                    <div class="input-box">
                        <input type="text" name="email" alt="email" id="email_address"
                               class="input-text required-entry validate-email"
                               value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>"/>
                    </div>
                </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>
        </div>
        <div class="buttons-set">
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <p class="back-link"><a href="<?php echo $this->helper('customer')->getLoginUrl() ?>">
                    <small>&laquo;</small><?php echo $this->__('Back to Login') ?></a></p>
            <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submit')) ?>"
                    class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        </div>
    </form>
</div>
<?php $loaderPath = $this->getSkinUrl('images/ajax-loader.gif', array('_secure' => true)) ?>
<div class="mobileloader">
    <div class="wait">
        <img src='<?php echo $loaderPath; ?>' width="64" height="64"/><br>Loading..
    </div>
</div>

<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    //]]>
</script>
<?php
$storeurl=Mage::getBaseUrl();
?>
<script>
    function  getBaseUrl() {
        return '<?php echo $storeurl; ?>';
    }
</script>