<tr>
    <td class="label"><?php echo $this->getElement()->getLabel(); ?></td>
    <td class="value" style="width:350px">
        <input type="text" class="input-text" style="width:50px" name="rate_from" value="<?php echo $this->getRateFrom(); ?>"/>
        &nbsp;&raquo;&nbsp;
        <input type="text" class="input-text" style="width:50px" name="rate_to" value="<?php echo $this->getRateTo(); ?>"/>
    </td>
</tr>
