<div class="buttons-googleplus-one">
    <script type="text/javascript">
        var gp = new RewardsGoogleplusOne('<?php echo $this->getOneUrl() ?>?url=<?php echo $this->getCurrentEncodedUrl()?>');
    </script>
    <a href="https://plus.google.com/share?url=<?php echo $this->getCurrentEncodedUrl()?>"
       onclick="gp.onPlus(); javascript:window.open(this.href, '',
            'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;">
        <img src="https://www.gstatic.com/images/icons/gplus-16.png" alt="Share on Google+"/>
    </a>
    <?php if ($this->getEstimatedEarnPoints() > 0): ?>
        <?php if ($this->isAuthorized() && !$this->isLiked()): ?>
            <div id='googleplus-message'>
                <?php echo $this->__(
                    'Plus this page and earn %s',
                    Mage::helper('rewards')->formatPoints($this->getEstimatedEarnPoints())
                ); ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>
</div>
