<?php
$helper = Mage::helper('giftcard');
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $giftCardCollection = $this->getCollection(); ?>
<div class="page-title">
    <h1><?php echo $this->__('My Gift Cards') ?></h1>
</div>
<?php echo $this->getPagerHtml(); ?>
<?php if($giftCardCollection->getSize()): ?>
    <table class="data-table" id="my-giftcard-table">
        <thead>
        <tr>
            <th><?php echo $this->__('Gift Card Code') ?></th>
            <th><?php echo $this->__('Balance') ?></th>
            <th><?php echo $this->__('Expired At') ?></th>
            <th><?php echo $this->__('Status') ?></th>
            <th>&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($giftCardCollection as $giftCard): ?>
            <tr>
                <td><?php echo $giftCard->getCode() ?></td>
                <td><?php echo $giftCard->getFormatedBalance() ?></td>

                <td><?php echo $giftCard->getData('expired_at')!=''?$this->formatDate($giftCard->getData('expired_at')):'-' ?></td>
                <td><?php echo $this->__($giftCard->getStatus()); ?></td>
                <td class="a-right">
                    <?php if ($giftCard->getType() != MT_Giftcard_Model_Giftcard::TYPE_REAL): ?>
                    <a href="<?php echo $helper->getCustomerDownloadPdfUrl($giftCard); ?>"><span class="nobr"><?php echo $this->__('Download (.pdf)') ?></span></a>
                    <?php endif;?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('my-giftcard-table');</script>
    <?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('Your gift card list is empty.'); ?></p>
<?php endif ?>
