<?php if ($items = $this->getItems()): ?>
<table cellspacing="0" cellpadding="0" border="0" width="650" style="border:1px solid #EAEAEA;">
    <thead>
    <tr>
        <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Gift Card Code') ?></th>
        <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Balance') ?></th>
        <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Status') ?></th>
        <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Valid to') ?></th>
    </tr>
    </thead>

    <tbody>
        <?php foreach ($this->getItems() as $giftCard): ?>
        <tr>
            <td style="font-size:13px; padding:3px 9px"><?php echo $giftCard->getCode();?></td>
            <td style="font-size:13px; padding:3px 9px"><?php echo $giftCard->getFormatedBalance();?></td>
            <td style="font-size:13px; padding:3px 9px"><?php echo $this->__($giftCard->getStatus());?></td>
            <td style="font-size:13px; padding:3px 9px"><?php echo $giftCard->getExpiredAt();?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>