<div class="buttons-facebook-like">
    <fb:like href="<?php echo $this->getEncodedPageUrl()?>" send="false" layout="button" show_faces="false" width="450" action="like" font="arial" colorscheme="light" ></fb:like>
    <?php if ($this->getEstimatedEarnPoints() > 0): ?>
        <?php if ($this->isAuthorized() && !$this->isLiked()): ?>
            <div id='facebook-message'>
                <?php echo $this->__('Like this page and earn %s',  Mage::helper('rewards')->formatPoints($this->getEstimatedEarnPoints())); ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>
</div>

<div class="mst-share-wrapper">
    <a class="mst-fb-share" style="text-decoration:none;" target="_blank" href="#" onclick="event.preventDefault(); facebookShare();">
        <span class="mst-fb-share-text"><?php echo $this->__('Share'); ?></span>
    </a>
</div>