<?php

/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Advancedreports
 * @version     0.2.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */

// Checking session dates for sales report
if (Mage::getSingleton('core/session')->getAdvancedReportDateOption() && Mage::app()->getRequest()->getParam('advanced_report_date_session') == 1) {
    if (Mage::getSingleton('core/session')->getAdvancedReportDateOption() == "Custom") {
        $_advanced_get_option = Mage::getSingleton('core/session')->getAdvancedReportDateOption();
        $_advanced_get_from = Mage::getSingleton('core/session')->getAdvancedReportDateFrom();
        $_advanced_get_to = Mage::getSingleton('core/session')->getAdvancedReportDateTo();
    } else {
        $_advanced_get_option = Mage::getSingleton('core/session')->getAdvancedReportDateOption();
    }
} else {
    $_advanced_get_option = Mage::app()->getRequest()->getParam('date_range_option');
    $_advanced_get_from = Mage::app()->getRequest()->getParam('from');
    $_advanced_get_to = Mage::app()->getRequest()->getParam('to');
}

// Assigning from and to date
if (!empty($_advanced_get_option)) {
    switch ($_advanced_get_option) {
        case "Today":
            // today interval
            $start_day = strtotime("-1 today midnight");
            $end_day = strtotime("-1 tomorrow midnight");
            $from = date("Y-m-d", $start_day);
            $to = date("Y-m-d", $end_day);
            $from_display = date("Y-m-d", $start_day);
            $to_display = date("Y-m-d", $start_day);
            break;
        case "Yesterday":
            // yesterday interval
            $start_day = strtotime("-1 yesterday midnight");
            $end_day = strtotime("-1 today midnight");
            $from = date("Y-m-d", $start_day);
            $to = date("Y-m-d", $end_day);
            $from_display = date("Y-m-d", $start_day);
            $to_display = date("Y-m-d", $start_day);
            break;
        case "LastWeek":
            // last week interval
            $t = date('d-m-Y');
            $to_day = date('l', strtotime($t));
            // if today is monday, take last monday
            if ($to_day == 'Monday') {
                $start_day = strtotime("-1 monday midnight");
                $end_day = strtotime("yesterday");
            } else {
                $start_day = strtotime("-2 monday midnight");
                $end_day = strtotime("-1 sunday midnight");
            }
            $from = date("Y-m-d", $start_day);
            $to = date("Y-m-d", $end_day);
            $to = date('Y-m-d', strtotime($to . ' + 1 day'));
            $from_display = $from;
            $to_display = date("Y-m-d", $end_day);
            break;
        case "LastMonth":
            // last month interval
            $from = date('Y-m-01', strtotime('last month'));
            $to = date('Y-m-t', strtotime('last month'));
            $to = date('Y-m-d', strtotime($to . ' + 1 day'));
            $from_display = $from;
            $to_display = date('Y-m-t', strtotime('last month'));
            break;
        case "Custom":
            // last custom interval
            $from = date('Y-m-d', strtotime($_advanced_get_from));
            $to = date('Y-m-d', strtotime($_advanced_get_to . ' + 1 day'));
            $from_display = $from;
            $to_display = date('Y-m-d', strtotime($_advanced_get_to));
            break;
        default:
            // last 30 interval
            $from = date('Y-m-d', strtotime('-30 day'));
            $to = date('Y-m-d', strtotime("-1 today midnight"));
            $to = date('Y-m-d', strtotime($to . ' + 1 day'));
            $from_display = $from;
            $to_display = date('Y-m-d', strtotime("-1 today midnight"));
    }
} else {
    // last 30 interval
    $from = date('Y-m-d', strtotime('-30 day'));
    $to = date('Y-m-d', strtotime("-1 today midnight"));
    $to = date('Y-m-d', strtotime($to . ' + 1 day'));
    $from_display = $from;
    $to_display = date('Y-m-d', strtotime("-1 today midnight"));
}

// Convert local date to db date
$db_from = Mage::getModel('core/date')->gmtDate(null, strtotime($from));
$db_to = Mage::getModel('core/date')->gmtDate(null, strtotime($to));

// Getting time to purchase collection
$carts = $this->advancedTimetopurchaseReportCollection($db_from, $db_to);

// Initizing time to puchase report data array
$timetopurchase = array();

// Initizing defualt values for data array
for ($inc = 0; $inc <= 10; $inc++) {
    $timetopurchase[$inc] = 0;
}
$timetopurchase['11-25'] = 0;
$timetopurchase['25+'] = 0;
$i = 0;
$j = 0;

// Calculating timetopurchase report data.
foreach ($carts as $value) {
    $date_u = Mage::getModel('core/date')->date(null, strtotime($value->getSfqUpdatedAt()));
    $date_c = Mage::getModel('core/date')->date(null, strtotime($value->getSfqCreatedAt()));
    $datediff = abs(strtotime($date_u) - strtotime($date_c));
    $nodays = intval(floor($datediff / 86400));

    if ($nodays > 10 && $nodays <= 25) {
        $timetopurchase['11-25'] = $i + 1;
        $i = $i + 1;
    } elseif ($nodays > 25) {
        $timetopurchase['25+'] = $j + 1;
        $j = $j + 1;
    } else {
        $timetopurchase[$nodays] = $timetopurchase[$nodays] + 1;
    }
}

// Calculating total no of transactions
$total_timetopurchase = array_sum($timetopurchase);

// Sorting time to purchase data array
ksort($timetopurchase);

// Calculating timetopurchase report chart data
$timetopurchase_data = '';
foreach ($timetopurchase as $key => $value) {
    $timetopurchase_data.="data.addRow(['{$key}', {$value}]);";
}
?>




<?php
// Today
$today_start_day = strtotime("-1 today midnight");
$today_from = date("Y-m-d", $today_start_day);
$today_to = date("Y-m-d", $today_start_day);

// Yesterday
$yesterday_start_day = strtotime("-1 yesterday midnight");
$yesterday_from = date("Y-m-d", $yesterday_start_day);
$yesterday_to = date("Y-m-d", $yesterday_start_day);

// Last week
$t = date('d-m-Y');
$to_day = date('l', strtotime($t));
// if today is monday, take last monday
if ($to_day == 'Monday') {
    $start_day = strtotime("-1 monday midnight");
    $end_day = strtotime("yesterday");
} else {
    $start_day = strtotime("-2 monday midnight");
    $end_day = strtotime("-1 sunday midnight");
}
$lastweek_from = date("Y-m-d", $start_day);
$lastweek_to = date("Y-m-d", $end_day);

// Last Month
$lastmonth_from = date('Y-m-01', strtotime('last month'));
$lastmonth_to = date('Y-m-t', strtotime('last month'));
?>

<input type="hidden" id="timetopurchase-revenue-today-date-from" value="<?php echo date('m/d/Y', strtotime($today_from)); ?>" />
<input type="hidden" id="timetopurchase-revenue-today-date-to" value="<?php echo date('m/d/Y', strtotime($today_to)); ?>" />
<input type="hidden" id="timetopurchase-revenue-yesterday-date-from" value="<?php echo date('m/d/Y', strtotime($yesterday_from)); ?>" />
<input type="hidden" id="timetopurchase-revenue-yesterday-date-to" value="<?php echo date('m/d/Y', strtotime($yesterday_to)); ?>" />
<input type="hidden" id="timetopurchase-revenue-lastweek-date-from" value="<?php echo date('m/d/Y', strtotime($lastweek_from)); ?>" />
<input type="hidden" id="timetopurchase-revenue-lastweek-date-to" value="<?php echo date('m/d/Y', strtotime($lastweek_to)); ?>" />
<input type="hidden" id="timetopurchase-revenue-lastmonth-date-from" value="<?php echo date('m/d/Y', strtotime($lastmonth_from)); ?>" />
<input type="hidden" id="timetopurchase-revenue-lastmonth-date-to" value="<?php echo date('m/d/Y', strtotime($lastmonth_to)); ?>" />
<!-- Time to purchase report hidden value for report generation -->
<input type="hidden" id="timetopurchase-revenue-custom-date-from" value="<?php echo date('m/d/Y', strtotime($from_display)); ?>" />
<input type="hidden" id="timetopurchase-revenue-custom-date-to" value="<?php echo date('m/d/Y', strtotime($to_display)); ?>" />
<!--<input type="hidden" id="timetopurchase_ajax_url" value="<?php echo Mage::helper("adminhtml")->getUrl("advancedreports/adminhtml_advancedreports/timetopurchase"); ?>" />-->
<!-- For reset drop down -->
<input type="hidden" id="timetopurchase_reset_dropdown" value="<?php
if (!empty($_advanced_get_option)) {
    echo Mage::helper('advancedreports')->__($_advanced_get_option);
} else {
    echo Mage::helper('advancedreports')->__('Custom');
}
?>" />
<!-- Time to purchase report wrapper -->
    <div class="advanced_report_wrapper" id="timetopurchase_advanced_report_wrapper">

        <!-- Time to purchase ajax loader -->
<!--        <div id="timetopurchase_report_ajax_load" style="display: none;" class="loading_img">
            <p><?php echo Mage::helper('advancedreports')->__('Please wait') . ' ...'; ?></p>
        </div>-->

        <h3 class="advanced_report_header content-header"> <span class="title_head"> <?php echo Mage::helper('advancedreports')->__('Time to Purchase Report'); ?></span>

            <!-- Date Picker -->

            <!-- Time to purchase report date picker -->
            <div class="advanced_date_picker">
                <span id="timetopurchase-report-date-range" class="report-date-range" >
                    <?php echo Date('M j, Y', strtotime($from_display)) . ' - ' . Date('M j, Y', strtotime($to_display)); ?>
                </span>
                <div id="timetopurchase-report-date-picker"  class="date_popup" style="display: none">

                    <div id="timetopurchase-advanced-report-datepicker"></div>

                    <div class="advanced-report-right">
                        <label for="daterange-select"><?php echo Mage::helper('advancedreports')->__('Date Range'); ?></label>
                        <select id="timetopurchase-date-range-select" name="daterange">

                            <option value="Custom" <?php
                            if (!empty($_advanced_get_option)) {
                                if ($_advanced_get_option == 'Custom') {
                                    echo 'selected';
                                }
                            }
                            ?>><?php echo Mage::helper('advancedreports')->__('Custom'); ?></option>
                            <option value="Today" <?php
                            if (!empty($_advanced_get_option)) {
                                if ($_advanced_get_option == 'Today') {
                                    echo 'selected';
                                }
                            }
                            ?>><?php echo Mage::helper('advancedreports')->__('Today'); ?></option>
                            <option value="Yesterday" <?php
                            if (!empty($_advanced_get_option)) {
                                if ($_advanced_get_option == 'Yesterday') {
                                    echo 'selected';
                                }
                            }
                            ?>><?php echo Mage::helper('advancedreports')->__('Yesterday'); ?></option>
                            <option value="LastWeek" <?php
                            if (!empty($_advanced_get_option)) {
                                if ($_advanced_get_option == 'LastWeek') {
                                    echo 'selected';
                                }
                            }
                            ?>><?php echo Mage::helper('advancedreports')->__('Last Week'); ?></option>
                            <option value="LastMonth" <?php
                            if (!empty($_advanced_get_option)) {
                                if ($_advanced_get_option == 'LastMonth') {
                                    echo 'selected';
                                }
                            }
                            ?>><?php echo Mage::helper('advancedreports')->__('Last Month'); ?></option>

                        </select>
                        <div style="clear: both;margin-bottom: 10px;"></div>
                        <input type="text" id="timetopurchase-custom-date-from" size="10"  <?php
                        if (!empty($_advanced_get_option)) {
                            if ($_advanced_get_option != "Custom") {
                                echo 'disabled';
                            }
                        }
                        ?>/>
                               <?php echo Mage::helper('advancedreports')->__('-'); ?>
                        <input type="text" id="timetopurchase-custom-date-to" size="10" <?php
                        if (!empty($_advanced_get_option)) {
                            if ($_advanced_get_option != "Custom") {
                                echo 'disabled';
                            }
                        }
                        ?>/>

                        <!-- Time to purchase date fields error message -->
                        <span  id="timetopurchase-report-err-msg" class="err-msg" style="display: none">
                            <?php echo Mage::helper('advancedreports')->__('Please select') . ' '; ?>
                            <b><?php echo Mage::helper('advancedreports')->__('from') . ' '; ?></b>
                            <?php echo Mage::helper('advancedreports')->__('and') . ' '; ?>
                            <b> <?php echo Mage::helper('advancedreports')->__('to') . ' '; ?></b>
                            <?php echo Mage::helper('advancedreports')->__('dates'); ?>
                        </span>
                        <span  id="timetopurchase-report-todate-err-msg" class="err-msg" style="display: none">
                            <?php echo Mage::helper('advancedreports')->__('Please select valid') . ' '; ?>
                            <b> <?php echo '"' . Mage::helper('advancedreports')->__('to') . '" '; ?></b>
                            <?php echo Mage::helper('advancedreports')->__('date') . ' '; ?>
                        </span>
                        <div style="clear: both;padding-bottom: 10px;border-bottom: 1px dotted #666;margin-bottom: 10px;"></div>
                        <a id="timetopurchase_report_apply"  href="javascript:void(0)" class="apply" onclick="timetopurchase_report_apply_click();" ><?php echo Mage::helper('advancedreports')->__('Apply'); ?></a>
                        <div style="position: relative; float:left;">
                            <div id="timetopurchase-report-disable-click-event">
                                <a><?php echo Mage::helper('advancedreports')->__('Cancel'); ?></a>
                            </div>
                            <a href="javascript:void(0)" id="timetopurchase-report-date-cancel" onclick="timetopurchasecancel();"><?php echo Mage::helper('advancedreports')->__('Cancel'); ?></a>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Time to purchase export option -->
            <div id="timetopurchaseexport">
                <span><?php echo Mage::helper('advancedreports')->__('Export As:'); ?></span>
                <a href="<?php echo Mage::helper("adminhtml")->getUrl("advancedreports/adminhtml_advancedreports/advancedReports/", array("from" => $from, "to" => $to, "report" => 'timetopurchase_csv')); ?>" class="csv"><img src="<?php echo $this->getSkinUrl('advancedreports/images/export_csv.png') ?>" width="25"  height="24" alt="<?php echo Mage::helper('advancedreports')->__('CSV'); ?>" title="<?php echo Mage::helper('advancedreports')->__('CSV'); ?>" /></a>
                <a href="<?php echo Mage::helper("adminhtml")->getUrl("advancedreports/adminhtml_advancedreports/advancedReports/", array("from" => $from, "to" => $to, "report" => 'timetopurchase_xml')); ?>" class="excel"><img src="<?php echo $this->getSkinUrl('advancedreports/images/export_xml.png') ?>" width="25"  height="24" alt="<?php echo Mage::helper('advancedreports')->__('XML'); ?>" title="<?php echo Mage::helper('advancedreports')->__('XML'); ?>" /></a>
            </div>

        </h3>

        <div class="total-transaction timetopurchase">
            <p class="text"><?php echo Mage::helper('advancedreports')->__('No of Transactions'); ?> </p>
            <p class="number"><?php echo $total_timetopurchase; ?></p>
        </div>
        <div style="clear: both;"></div>

        <!-- Time to purchase report chart container -->
        <div class="timetopurchase_chart_container">
            <div class="timetopurchase_chart_table">
                <table id="timetopurchase-advanced-report-table"  border="0"  cellpadding="0" cellspacing="0">
                    <thead>
                        <tr>
                            <th align="left" class="text_left" width="30%"><?php echo Mage::helper('advancedreports')->__('Days to Transaction'); ?></th>
                            <th align="right" class="text_right" width="30%"><?php echo Mage::helper('advancedreports')->__('Transactions'); ?></th>
                            <th align="right" class="text_right last_td" width="40%"><?php echo Mage::helper('advancedreports')->__('Percentage of total %'); ?></th>

                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $sno = 1;
                        if ($total_timetopurchase >= 1) {
                            foreach ($timetopurchase as $key => $value) {
                                ?>
                                <tr class="advanced-report-data <?php
                                if ($sno % 2 == 0) {
                                    echo 'advanced-report-even';
                                }
                                ?>">
                                    <td align="left" ><?php echo $key; ?></td>
                                    <td align="left" class="transactions" ><?php echo $value; ?></td>

                                    <td align="left"  class="percentage" >
                                        <span class="advanced_progress_wrap">
                                            <span class="advanced_progress_bar" style="width:<?php echo round(($value / $total_timetopurchase * 100), 2) . '%'; ?>"><img src="<?php echo $this->getSkinUrl('advancedreports/images/bar.jpg') ?>" width="320"  height="12" alt="" /></span>
                                            <span class="advanced-percentage"><?php echo round(($value / $total_timetopurchase * 100), 2) . ' %'; ?></span>
                                        </span>
                                    </td>
                                </tr>
                                <?php
                                $sno = $sno + 1;
                            }
                        }
                        ?>


                    </tbody>

                    <?php
// checking for table data
                    if ($total_timetopurchase < 1) {
                        ?>
                        <tfoot><tr><td colspan="3" align="center"> <?php echo Mage::helper('advancedreports')->__('No data found') . '.'; ?> </td></tr></tfoot>
                    <?php } // end if for checking table data    ?>
                </table>

            </div>
            <div id="timetopurchase_chart_div"></div>
        </div>



        <!-- Time to purchase chart -->


            <!--    <script type="text/javascript" src="https://www.google.com/jsapi"></script>-->

        <!-- CODE FOR LESS THAN IE 8 VERSIONS -->
        <!--[if lt IE 9]>
        <script type="text/javascript">
             jq(document).ready(function() {
             setTimeout(timetopurchasedrawChart,300);
                jq("#advancedreports_tabs_timetopurchase_section").click(function(event) {
                    setTimeout(timetopurchasedrawChart,300);
                                });
            });
        </script>
        <![endif]-->

        <!-- Generating time to purchase report chart -->
        <script type="text/javascript">
    //        google.load('visualization', '1.0', {'packages': ['corechart']});
    //        google.setOnLoadCallback(timetopurchasedrawChart);

                            // Calculating time to purchase report chart
                            function timetopurchasedrawChart() {
                                var data = new google.visualization.DataTable();
                                data.addColumn('string', '<?php echo Mage::helper('advancedreports')->__("Days to Transaction"); ?>');
                                data.addColumn('number', '<?php echo Mage::helper('advancedreports')->__("Transactions"); ?>');
    <?php
    echo $timetopurchase_data;
    ?>
                                var options = {
                                    is3D: true,
                                    'width': 324,
                                    'height': 250};
                                var chart = new google.visualization.PieChart(document.getElementById('timetopurchase_chart_div'));
                                chart.draw(data, options);
                            }
        </script>
    </div>

    <!-- Calling Time to purchase chart  -->
    <script type="text/javascript">
        jq(document).ready(function() {
            setTimeout(timetopurchasedrawChart, 200);
            jq("#advancedreports_tabs_timetopurchase_section").click(function(event) {
                timetopurchasedrawChart();
            });
        });
    </script>

    <script type="text/javascript">
        jq(document).ready(function() {
            // Reset timetopuchase datepicker
            jq("#timetopurchase-report-date-cancel").click(function() {
                var timetopurchase_reset = jq("#timetopurchase_reset_dropdown").val();
                jq("#timetopurchase-advanced-report-datepicker").datepicker("refresh");
                jq("#timetopurchase-date-range-select").val(timetopurchase_reset);
                jq("#timetopurchase-report-err-msg").hide();
                jq("#timetopurchase-custom-date-from").val('');
                jq("#timetopurchase-custom-date-to").val('');
            });

            // Assign date to text fields.
            jq("#timetopurchase-report-date-range").click(function() {

                jq("#timetopurchase-custom-date-from").val(jq("#timetopurchase-revenue-custom-date-from").val());
                jq("#timetopurchase-custom-date-to").val(jq("#timetopurchase-revenue-custom-date-to").val());
            });
            jq("#timetopurchase-report-date-cancel").click(function() {
                jq("#timetopurchase-custom-date-from").val(jq("#timetopurchase-revenue-custom-date-from").val());
                jq("#timetopurchase-custom-date-to").val(jq("#timetopurchase-revenue-custom-date-to").val());
            });

            // Reset timetopurchase datepicker
            jq("#timetopurchase-report-date-cancel").click(function() {
                jq("#timetopurchase-advanced-report-datepicker").datepicker("refresh");
                jq("#timetopurchase-report-todate-err-msg").hide();
                jq("#timetopurchase-report-disable-click-event").show();
            });
            jq('#timetopurchase-date-range-select').change(function() {

                jq("#timetopurchase-report-disable-click-event").hide();
                if (jq(this).val() != "Custom")
                {

                    jq("#timetopurchase-advanced-report-datepicker").datepicker("destroy");

                    jq("#timetopurchase-advanced-report-datepicker").datepicker({
                        monthNames: ['<?php echo Mage::helper('advancedreports')->__('January'); ?>', '<?php echo Mage::helper('advancedreports')->__('February'); ?>', '<?php echo Mage::helper('advancedreports')->__('March'); ?>', '<?php echo Mage::helper('advancedreports')->__('April'); ?>', '<?php echo Mage::helper('advancedreports')->__('May'); ?>', '<?php echo Mage::helper('advancedreports')->__('June'); ?>',
                            '<?php echo Mage::helper('advancedreports')->__('July'); ?>', '<?php echo Mage::helper('advancedreports')->__('August'); ?>', '<?php echo Mage::helper('advancedreports')->__('September'); ?>', '<?php echo Mage::helper('advancedreports')->__('October'); ?>', '<?php echo Mage::helper('advancedreports')->__('November'); ?>', '<?php echo Mage::helper('advancedreports')->__('December'); ?>'],
                       // dayNamesMin: ['Mo', 'Tu','We','Th','Fr','Sa','Su'],
                        maxDate: 0,
                        yearRange: "-100:+0",
                        numberOfMonths: 3,
                        beforeShowDay: function(date) {

                            if (jq("#timetopurchase-date-range-select").val() == "Today")
                            {
                                var from = jq("#timetopurchase-revenue-today-date-from").val();
                                var to = jq("#timetopurchase-revenue-today-date-to").val();
                                jq("#timetopurchase-custom-date-from").val(from);
                                jq("#timetopurchase-custom-date-to").val(to);
                            }
                            else if (jq("#timetopurchase-date-range-select").val() == "Yesterday")
                            {
                                var from = jq("#timetopurchase-revenue-yesterday-date-from").val();
                                var to = jq("#timetopurchase-revenue-yesterday-date-to").val();
                                jq("#timetopurchase-custom-date-from").val(from);
                                jq("#timetopurchase-custom-date-to").val(to);
                            }
                            else if (jq("#timetopurchase-date-range-select").val() == "LastWeek")
                            {
                                var from = jq("#timetopurchase-revenue-lastweek-date-from").val();
                                var to = jq("#timetopurchase-revenue-lastweek-date-to").val();
                                jq("#timetopurchase-custom-date-from").val(from);
                                jq("#timetopurchase-custom-date-to").val(to);
                            }
                            else if (jq("#timetopurchase-date-range-select").val() == "LastMonth")
                            {
                                var from = jq("#timetopurchase-revenue-lastmonth-date-from").val();
                                var to = jq("#timetopurchase-revenue-lastmonth-date-to").val();
                                jq("#timetopurchase-custom-date-from").val(from);
                                jq("#timetopurchase-custom-date-to").val(to);

                            }
                            else
                            {
                            }

                            var date1 = jq.datepicker.parseDate(jq.datepicker._defaults.dateFormat, jq("#timetopurchase-custom-date-from").val());
                            var date2 = jq.datepicker.parseDate(jq.datepicker._defaults.dateFormat, jq("#timetopurchase-custom-date-to").val());
                            return [true, date1 && ((date.getTime() == date1.getTime()) || (date2 && date >= date1 && date <= date2)) ? "dp-highlight" : ""];


                        },
                        onSelect: function(dateText, inst) {
                            var date1 = jq.datepicker.parseDate(jq.datepicker._defaults.dateFormat, jq("#timetopurchase-custom-date-from").val());
                            var date2 = jq.datepicker.parseDate(jq.datepicker._defaults.dateFormat, jq("#timetopurchase-custom-date-to").val());
                            jq("#timetopurchase-date-range-select").val("Custom");
                            jq("#timetopurchase-custom-date-from").removeAttr("disabled");
                            jq("#timetopurchase-custom-date-to").removeAttr("disabled");
                            jq("#timetopurchase-report-disable-click-event").hide();
                            if (!date1 || date2) {
                                jq("#timetopurchase-custom-date-from").val(dateText);
                                jq("#timetopurchase-custom-date-to").val("");
                                jq(this).datepicker();
                            } else {

                                var checkdate = jq.datepicker.parseDate(jq.datepicker._defaults.dateFormat, jq("#timetopurchase-custom-date-from").val());
                                var checkdateText = jq.datepicker.parseDate(jq.datepicker._defaults.dateFormat, dateText);
                                if (checkdate > checkdateText)
                                {
                                    jq("#timetopurchase-report-todate-err-msg").show();
                                    return;
                                }
                                jq("#timetopurchase-report-todate-err-msg").hide();
                                jq("#timetopurchase-custom-date-to").val(dateText);
                                jq(this).datepicker();
                            }
                            jq("#timetopurchase-report-err-msg").hide();

                        }
                    }
                    );

                }
                jq("#timetopurchase-report-todate-err-msg").hide();
            });

            // Display and hide timetopurchase datepicker
            jq('#timetopurchase-report-date-range').click(function() {
                jq('#timetopurchase-report-date-picker').slideToggle('fast');
                jq('#timetopurchase-report-date-range').toggleClass('arrowdown');
            });

            // Hide time to purchase datepicker div

            jq(document).click(function() {
                jq("#timetopurchase-report-date-picker").hide();
                jq('#timetopurchase-report-date-range').removeClass('arrowdown');
            });

            jq('#timetopurchase-report-date-picker,#timetopurchase-report-date-range').click(function(event) {
                event.stopPropagation();
            });

            // Enable or disable datepicker text fields

            jq("#timetopurchase-date-range-select").change(function() {

                if (jq("#timetopurchase-date-range-select").val() == 'Custom')
                {
                    jq("#timetopurchase-custom-date-from").removeAttr("disabled");
                    jq("#timetopurchase-custom-date-to").removeAttr("disabled");

                    jq("#timetopurchase-custom-date-from").val('');
                    jq("#timetopurchase-custom-date-to").val('');
                    jq("#timetopurchase-advanced-report-datepicker").datepicker("refresh");

                }
                else
                {
                    jq("#timetopurchase-custom-date-from").attr("disabled", "disabled");
                    jq("#timetopurchase-custom-date-to").attr("disabled", "disabled");
                }
            });
        });

    //  Time to purchase report  date picker
        jq(function() {
            jq("#timetopurchase-advanced-report-datepicker").datepicker({
                monthNames: ['<?php echo Mage::helper('advancedreports')->__('January'); ?>', '<?php echo Mage::helper('advancedreports')->__('February'); ?>', '<?php echo Mage::helper('advancedreports')->__('March'); ?>', '<?php echo Mage::helper('advancedreports')->__('April'); ?>', '<?php echo Mage::helper('advancedreports')->__('May'); ?>', '<?php echo Mage::helper('advancedreports')->__('June'); ?>',
                    '<?php echo Mage::helper('advancedreports')->__('July'); ?>', '<?php echo Mage::helper('advancedreports')->__('August'); ?>', '<?php echo Mage::helper('advancedreports')->__('September'); ?>', '<?php echo Mage::helper('advancedreports')->__('October'); ?>', '<?php echo Mage::helper('advancedreports')->__('November'); ?>', '<?php echo Mage::helper('advancedreports')->__('December'); ?>'],
               // dayNamesMin: ['Mo', 'Tu','We','Th','Fr','Sa','Su'],
                maxDate: 0,
                yearRange: "-100:+0",
                numberOfMonths: 3,
                beforeShowDay: function(date) {

                    if (jq("#timetopurchase-custom-date-from").val() == '' && jq("#timetopurchase-custom-date-to").val() == '')
                    {
                        var d_h1 = jq("#timetopurchase-revenue-custom-date-from").val();
                        var d_h2 = jq("#timetopurchase-revenue-custom-date-to").val();
                        var date1 = jq.datepicker.parseDate(jq.datepicker._defaults.dateFormat, d_h1);
                        var date2 = jq.datepicker.parseDate(jq.datepicker._defaults.dateFormat, d_h2);
                        return [true, date1 && ((date.getTime() == date1.getTime()) || (date2 && date >= date1 && date <= date2)) ? "dp-highlight" : ""];
                    }

                    var date1 = jq.datepicker.parseDate(jq.datepicker._defaults.dateFormat, jq("#timetopurchase-custom-date-from").val());
                    var date2 = jq.datepicker.parseDate(jq.datepicker._defaults.dateFormat, jq("#timetopurchase-custom-date-to").val());
                    return [true, date1 && ((date.getTime() == date1.getTime()) || (date2 && date >= date1 && date <= date2)) ? "dp-highlight" : ""];
                },
                onSelect: function(dateText, inst) {
                    var date1 = jq.datepicker.parseDate(jq.datepicker._defaults.dateFormat, jq("#timetopurchase-custom-date-from").val());
                    var date2 = jq.datepicker.parseDate(jq.datepicker._defaults.dateFormat, jq("#timetopurchase-custom-date-to").val());
                    jq("#timetopurchase-date-range-select").val("Custom");
                    jq("#timetopurchase-custom-date-from").removeAttr("disabled");
                    jq("#timetopurchase-custom-date-to").removeAttr("disabled");
                    jq("#timetopurchase-report-disable-click-event").hide();
                    if (!date1 || date2) {
                        jq("#timetopurchase-custom-date-from").val(dateText);
                        jq("#timetopurchase-custom-date-to").val("");
                        jq(this).datepicker();
                    } else {

                        var checkdate = jq.datepicker.parseDate(jq.datepicker._defaults.dateFormat, jq("#timetopurchase-custom-date-from").val());
                        var checkdateText = jq.datepicker.parseDate(jq.datepicker._defaults.dateFormat, dateText);
                        if (checkdate > checkdateText)
                        {
                            jq("#timetopurchase-report-todate-err-msg").show();
                            return;
                        }
                        jq("#timetopurchase-report-todate-err-msg").hide();

                        jq("#timetopurchase-custom-date-to").val(dateText);
                        jq(this).datepicker();
                    }
                    jq("#timetopurchase-report-err-msg").hide();

                }
            }
            );
        });
    </script>


    <?php
// Setting session for advanced report date
    if (Mage::app()->getRequest()->getParam('advanced_session') == 1) {
        if (Mage::getSingleton('core/session')->getAdvancedReportDateOption()) {
            Mage::getSingleton('core/session')->unsAdvancedReportDateOption();
            Mage::getSingleton('core/session')->unsAdvancedReportDateFrom();
            Mage::getSingleton('core/session')->unsAdvancedReportDateTo();
        }
        $advanced_report_date_option = Mage::app()->getRequest()->getParam('date_range_option');
        $advanced_report_date_from = Mage::app()->getRequest()->getParam('from');
        $advanced_report_date_to = Mage::app()->getRequest()->getParam('to');
        Mage::getSingleton('core/session')->setAdvancedReportDateOption($advanced_report_date_option);
        Mage::getSingleton('core/session')->setAdvancedReportDateFrom($advanced_report_date_from);
        Mage::getSingleton('core/session')->setAdvancedReportDateTo($advanced_report_date_to);
    }
    ?>