<script type="text/javascript">
<!--
<?php $myBlock = $this->getLayout()->getBlock('customerGrid'); ?>
<?php if( is_object($myBlock) && $myBlock->getJsObjectName() ): ?>
    var checkBoxes = $H(<?php echo $myBlock->_getUsers(true) ?>);
    var warning = false;
    if (checkBoxes.size() > 0) {
        warning = true;
    }
    $('in_transaction_user').value = checkBoxes.toQueryString();

    function registerUserRole(grid, element, checked)
    {
        if (checked) {
            checkBoxes.set(element.value, 0);
        } else {
            checkBoxes.unset(element.value);
        }
        $('in_transaction_user').value = checkBoxes.toQueryString();
        grid.reloadParams = {'in_transaction_user[]':checkBoxes.keys()};
    }

    function transactionUsersRowClick(grid, event)
    {
        var trElement = Event.findElement(event, 'tr');
        var isInput   = Event.element(event).tagName == 'INPUT';
        if (trElement) {
            var checkbox = Element.getElementsBySelector(trElement, 'input');
            if(checkbox[0]){
                var checked = isInput ? checkbox[0].checked : !checkbox[0].checked;
                if (checked) {
                    checkbox[0].checked = true;
                    // if ( confirm("<?php echo $this->__('Warning!\r\nThis action will remove this user from already assigned transaction\r\nAre you sure?') ?>") ) {
                        checkBoxes.set(checkbox[0].value, checked);
                        varienElementMethods.setHasChanges(checkbox[0]);
                    // } else {
                    //     checkbox[0].checked = false;
                    // }
                    // warning = false;
                } else {
                    checkBoxes.unset(checkbox[0].value);
                }

                $('in_transaction_user').value = checkBoxes.toQueryString();
                grid.reloadParams = {'in_transaction_user[]':checkBoxes.keys()};
            }
        }
    }

    function transactionUsersRowInit(grid, row)
    {
        var checkbox = $(row).getElementsByClassName('checkbox')[0];
        if (checkbox) {
            if (checkbox.checked) {
                checkBoxes.set(checkbox.value, checkbox.checked);
            } else {
                checkBoxes.unset(checkbox.value);
            }

            $('in_transaction_user').value = checkBoxes.toQueryString();
            grid.reloadParams = {'in_transaction_user[]':checkBoxes.keys()};
        }
    }

<?php echo $myBlock->getJsObjectName() ?>.rowClickCallback = transactionUsersRowClick;
<?php echo $myBlock->getJsObjectName() ?>.initRowCallback = transactionUsersRowInit;
<?php echo $myBlock->getJsObjectName() ?>.checkboxCheckCallback = registerUserRole;

<?php echo $myBlock->getJsObjectName() ?>.rows.each(function(row){transactionUsersRowInit(<?php echo $myBlock->getJsObjectName() ?>, row)});
    $('in_transaction_user_old').value = $('in_transaction_user').value;
<?php endif; ?>
//-->
</script>
